# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cobra}
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["matthew jording"]
  s.date = %q{2011-02-07}
  s.default_executable = %q{cobra}
  s.description = %q{An extension of the cijoe project now more descriptive}
  s.email = %q{mjording@opengotham.com}
  s.executables = ["cobra"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "lib/cobra.rb",
    "lib/cobra/build.rb",
    "lib/cobra/campfire.rb",
    "lib/cobra/commit.rb",
    "lib/cobra/config.rb",
    "lib/cobra/public/Cobra.gif",
    "lib/cobra/public/favicon.ico",
    "lib/cobra/public/favicon.png",
    "lib/cobra/public/screen.css",
    "lib/cobra/server.rb",
    "lib/cobra/version.rb",
    "lib/cobra/views/template.erb"
  ]
  s.homepage = %q{http://github.com/OpenGotham/cobra}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An extension of the cijoe project}
  s.test_files = [
    "test/helper.rb",
    "test/test_cobra.rb",
    "test/test_cobra_server.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<unicorn>, [">= 0"])
      s.add_runtime_dependency(%q<choice>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<unicorn>, [">= 0"])
      s.add_dependency(%q<choice>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<unicorn>, [">= 0"])
    s.add_dependency(%q<choice>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
  end
end

